name: wuliaotuapp
version: 3


handlers:
- url: /static
  static_dir: static


libraries:
- name: PIL
  version: "1.1.7"

- name: tornado
  version: "2.1.1"

- name: MySQLdb
  version: "1.2.3"


cron:
  - description: fetch_jandan
    url: fetch_jandan
    schedule: "*/5 * * * *"